CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS clothes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  image_url TEXT,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  color TEXT,
  season TEXT,
  style TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS clothes_user_created_idx
  ON clothes (user_id, created_at DESC);

UPDATE clothes SET category = 'shirts' WHERE category = 'tops';

CREATE TABLE IF NOT EXISTS outfits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS outfits_user_created_idx
  ON outfits (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS outfit_clothes (
  outfit_id BIGINT NOT NULL REFERENCES outfits(id) ON DELETE CASCADE,
  clothes_id BIGINT NOT NULL REFERENCES clothes(id) ON DELETE CASCADE,
  PRIMARY KEY (outfit_id, clothes_id)
);

CREATE TABLE IF NOT EXISTS wear_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  outfit_id BIGINT REFERENCES outfits(id) ON DELETE SET NULL,
  worn_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  notes TEXT
);

CREATE INDEX IF NOT EXISTS wear_history_user_worn_idx
  ON wear_history (user_id, worn_at DESC);
